# Generated by Django 5.2 on 2026-01-02 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorsStates',
            fields=[
                ('measuring_point', models.TextField(primary_key=True, serialize=False)),
                ('sensor_state', models.TextField(blank=True, null=True)),
                ('last_registered_malfunction', models.TextField(blank=True, null=True)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'db_table': 'sensor_states',
            },
        ),
    ]
